import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings("ignore")

# -----------------------------------------------
# Load the player data generated by simulator.py
# -----------------------------------------------

def load_data():
    df = pd.read_csv("player_data.csv")
    return df


# -----------------------------------------------
# These are the behavioral features the model
# will use to detect anomalies. It does NOT use
# player_id, player_name, or is_cheater.
# The model learns purely from behavior.
# -----------------------------------------------

FEATURES = [
    "avg_velocity",
    "max_velocity",
    "accuracy",
    "actions_per_sec",
    "score_per_min",
    "headshot_rate",
    "session_duration"
]


# -----------------------------------------------
# Train the Isolation Forest model only on
# normal player data. The model learns what
# normal behavior looks like.
# -----------------------------------------------

def train_model(df):
    normal_players = df[df["is_cheater"] == False]
    X_train = normal_players[FEATURES]

    # Normalize the data so all features are on the same scale
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)

    # Train Isolation Forest
    # contamination=0.05 means we expect roughly 5% anomalies
    model = IsolationForest(
        n_estimators=200,
        contamination=0.05,
        random_state=42
    )
    model.fit(X_train_scaled)

    print(f"Model trained successfully on {len(normal_players)} normal players.")

    return model, scaler


# -----------------------------------------------
# Run the model on ALL 200 players and see
# who it flags as suspicious
# -----------------------------------------------

def detect_cheaters(df, model, scaler):
    X_all = df[FEATURES]
    X_all_scaled = scaler.transform(X_all)

    # Isolation Forest returns -1 for anomaly, 1 for normal
    predictions = model.predict(X_all_scaled)

    # Anomaly score: more negative = more suspicious
    scores = model.decision_function(X_all_scaled)

    df = df.copy()
    df["anomaly_flag"] = predictions
    df["suspicion_score"] = np.round(-scores, 4)  # flip so higher = more suspicious

    return df


# -----------------------------------------------
# Print a clean report of results
# -----------------------------------------------

def print_report(df):
    flagged = df[df["anomaly_flag"] == -1]
    not_flagged = df[df["anomaly_flag"] == 1]

    print("\n========================================")
    print("       ANTI-CHEAT DETECTION REPORT      ")
    print("========================================")
    print(f"Total players analyzed : {len(df)}")
    print(f"Players flagged        : {len(flagged)}")
    print(f"Players cleared        : {len(not_flagged)}")

    print("\n--- FLAGGED PLAYERS ---")
    report_cols = ["player_id", "player_name", "cheat_type", 
                   "suspicion_score", "accuracy", "avg_velocity", 
                   "score_per_min", "headshot_rate", "actions_per_sec"]
    
    print(flagged[report_cols].sort_values(
        "suspicion_score", ascending=False
    ).to_string(index=False))

    print("\n--- DETECTION ACCURACY ---")
    actual_cheaters   = set(df[df["is_cheater"] == True]["player_id"])
    flagged_players   = set(flagged["player_id"])

    true_positives    = actual_cheaters & flagged_players
    false_positives   = flagged_players - actual_cheaters
    false_negatives   = actual_cheaters - flagged_players

    print(f"Actual cheaters in dataset     : {len(actual_cheaters)}")
    print(f"Correctly caught (TP)          : {len(true_positives)}")
    print(f"Innocent players wrongly flagged (FP) : {len(false_positives)}")
    print(f"Cheaters who slipped through (FN)     : {len(false_negatives)}")

    if true_positives:
        print(f"\nCheaters correctly identified  : {', '.join(true_positives)}")
    if false_positives:
        print(f"Innocent players flagged       : {', '.join(false_positives)}")
    if false_negatives:
        print(f"Cheaters missed                : {', '.join(false_negatives)}")


# -----------------------------------------------
# Main execution
# -----------------------------------------------

if __name__ == "__main__":
    df              = load_data()
    model, scaler   = train_model(df)
    results         = detect_cheaters(df, model, scaler)
    print_report(results)

    results.to_csv("detection_results.csv", index=False)
    print("\nFull results saved to detection_results.csv")